### ISSUE TITLE
Token nie działa

### ISSUE THREAD

**Issue by KubaZ2** [Smugaski/my-discord-token#1]
Token nie działa

**Comment by Smugaski** [comment]
juz naprawiam

**Comment by Smugaski** [comment]
powinno dzialac

**Comment by KubaZ2** [comment]
Nadal nie działa

**Comment by Maciej-dev** [comment]
Spróbuj napraić.

**Comment by klapouch** [comment]
nareperuj

**Comment by Maciej-dev** [comment]
Cześć kłapouch!

**Comment by Smugaski** [comment]
![28DC2D0D-5BF6-4009-B186-3E9A6A6BFAD7](https://user-images.githubusercontent.com/73793685/145720225-530409bf-b520-4f10-ad28-6278e922ce4b.jpeg)
